src/Entity/Admin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminRepository")
 * @ORM\Table(name="`admin`")
 */
class Admin implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function getSalt(){
        return null;
    }

    public function getRoles(){
        return ['ROLE_ADMIN'];
    }

    public function eraseCredentials()
    {
    }
}

src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $source;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->Introduction;
    }

    public function setIntroduction(string $Introduction): self
    {
        $this->Introduction = $Introduction;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(?string $source): self
    {
        $this->source = $source;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog")
     */
    public function blog(ArticleRepository $articleRepository)
    {

        $articles = $articleRepository-> findAll();
        return $this->render('blog/blog.html.twig', [
            'controller_name' => 'BlogController',
            'articles' => $articles,
        ]);
    }
    

     /**
     * @route("/blog/{id}/view", name="blog_view")
     */
    public function view(Article $article){
        return $this->render('blog/view.html.twig', [
            'controller_name' => 'bienvenue sur l\'article', 
            'article' => $article
            ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="home")
     */
    public function index()
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'Page d\'acceuil',
        ]);
    }

    /**
     * @Route("/home/contact", name="contact")
     */
    public function contact()
    {
        return $this->render('home/contact.html.twig', [
            'controller_name' => 'Page de contact',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />

    <title>
      {% block title %}
        Welcome!
      {% endblock %}
    </title>
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous" />
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/bootstrapdarkly.min.css" />
    

    <script src="https://kit.fontawesome.com/7c09c4a3ab.js"
      crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock %}
  </head>
  <body>
    {% include 'include/navbar.html.twig' %}

    {% block body %}
    {% endblock %}
    {% block javascripts %}
    {% endblock %}

    {% include 'include/article.html.twig' %}

    {% include 'include/pagination.html.twig' %}

    {% include 'include/articles.html.twig' %}

    {% include 'include/pagination.html.twig' %}
    
    {% include 'include/footer.html.twig' %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"></script>
  </body>
</html>

templates/blog/blog.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Hello BlogController!
{% endblock %}

{% block body %}
  <h1>
    Hello {{ controller_name }}! ✅
  </h1>

  {% for article in articles %}
    <div class=" card my-3 p-4 col-12">
      <h2 class="container">
        {{ article.title }}
      </h2>

      
      <p class=" lead">
        {{ article.introduction }}
      </p>
      <p class="lead">
        <img class="fit-picture" src="{{ article.image }}" alt="" />
      </p>
      
      <hr class="my-2" />
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{{ path('blog_view', { id: article.id }) }}" role="button">
          Voir plus ...
        </a>
      </p>
      <p class="lead">
        {{ article.source }}
      </p>
    </div>
  {% endfor %}
{% endblock %}

templates/blog/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Hello BlogController!
{% endblock %}

{% block body %}
  <h1>
    Hello {{ controller_name }}! ✅
  </h1>

 


<div class=" card my-3 p-4 col-12">
      <h2 class="container">
        {{ article.title }}
      </h2>
<p class=" lead">
        {{ article.introduction }}
      </p>
      
<p class="lead">
        <img class="fit-picture" src="{{ article.image }}" alt="" />
      </p>

      <p class=" lead">
        {{ article.contenu }}
      </p>
      
      
      <hr class="my-2" />
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{{ path('blog')}}" role="button">
          Retour
        </a>
      </p>
      <p class="lead">
        {{ article.source }}
      </p>
    </div>



 
{% endblock %}

templates/home/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>
 
 <p>Salut et bienvenue sur la page de contact</p>


</div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

{% endblock %}

templates/include/article.html.twig
<div class="container d-flex flex-direction-row">
  <div class="card my-3 p-4 col-8">
    
       <h1 class="display-5">Bienvenue sur la {{ controller_name }}! ✅</h1>
    
    <p class="lead">
      This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information. This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.
    </p>
    <hr class="my-2" />
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="#" role="button">Voir plus ...</a>
    </p>
    <div class="card-footer text-muted">
    2 days ago
  </div>
  </div>



  <div class="col-4">
    <div class="card p-4 my-3 col-12">
      <form class="form-inline">
        <input class="form-control mr-2" type="text" placeholder="Recherche" />
        <button class="btn btn-secondary" type="submit">
          GO!!!
        </button>
      </form>
    </div>

<div class="p-4 mb-3 col-12 d-flex justify-content-between">
<i class="fab fa-facebook fa-3x"></i>
 <i class="fab fa-twitter fa-3x"></i>
 <i class="fab fa-snapchat fa-3x"></i>
 <i class="fab fa-instagram fa-3x"></i>

</div>

    <div class="">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link px-4 active" data-toggle="tab" href="#popular">Populaire</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-4" data-toggle="tab" href="#recent">Recent</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-4" data-toggle="tab" href="#cate">Categorie</a>
        </li>
       
      </ul>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active show" id="popular">
         
        <ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >
    Html/Css 
  </a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Bootstrap</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >Php</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Ajax</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Symfony</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >Javascript</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > C++</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
     <a href="#" >Java</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
   <a href="#" > Phyton</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
</ul>
        </div>
        <div class="tab-pane fade" id="recent">
         
           <ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >
    Html/Css 
  </a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Bootstrap</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >Php</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Ajax</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Symfony</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >Javascript</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > C++</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
     <a href="#" >Java</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
   <a href="#" > Phyton</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
</ul>
        </div>
        <div class="tab-pane fade" id="cate">
          
          <ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >
    Html/Css 
  </a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Bootstrap</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >Php</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Ajax</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > Symfony</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" >Javascript</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="#" > C++</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
     <a href="#" >Java</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
   <a href="#" > Phyton</a>
    <span class="badge badge-primary badge-pill">0</span>
  </li>
</ul>
         
        </div>
      </div>
    </div>
  </div>
</div>

templates/include/articles.html.twig
<div class="container">
  <div class="card my-3 p-4 col-12">
    
       <h2 class="">Html5</h2>
    
    <p class="lead">
      This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information. This is a simple hero unit, a simple jumbotron-style component for calling
      
    </p>
    <hr class="my-2" />
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="#" role="button">Voir plus ...</a>
    </p>
  </div>



<div class="card my-3 p-4 col-12">
    
       <h2 class="">Css3</h2>
    
    <p class="lead">
      This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information. This is a simple hero unit, a simple jumbotron-style component for calling
      
    </p>
    <hr class="my-2" />
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="#" role="button">Voir plus ...</a>
    </p>
  </div>



















  </div>

templates/include/footer.html.twig
<!-- Footer -->
    <footer class="page-footer font-small bg-primary">

  <!-- Footer Links -->
     <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4 ">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Very long link 1</a>
          </li>
          <li>
            <a href="#!">Very long link 2</a>
          </li>
          <li>
            <a href="#!">Very long link 3</a>
          </li>
          <li>
            <a href="#!">Very long link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled ">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled ">
          <li >
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 ">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/include/navbar.html.twig
<!-- nav -->
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="{{ path('home') }}">
    <i class="fas fa-meteor fa-2x"></i>
  </a>
  <button class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item"><a class="nav-link" href="#">Devenir dev</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Cours</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ path('blog') }}">Blog</a></li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ path('contact') }}">Contact</a>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="#">Connexion</a>
        </li>
        <div class="form-group">
        <i class="far fa-moon"></i>/<i class="far fa-sun"></i>
          <div class="custom-control custom-switch">
          
            <input type="checkbox"
              class="custom-control-input"
              id="customSwitch1" />
            <label class="custom-control-label" for="customSwitch1">
              
            </label>
          </div>
        </div>

        
      </ul>
    </form>
  </div>
</nav>
<!-- nav -->

templates/include/pagination.html.twig
<!-- pagination -->
<section class="d-flex justify-content-center my-5">
<div>
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" href="#">&laquo;</a>
    </li>
    <li class="page-item active">
      <a class="page-link" href="#">1</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">3</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">4</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">5</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">&raquo;</a>
    </li>
  </ul>
</div>
</section>
<!-- pagination -->